### ISSUE TITLE
Upgrading to Moltin to version 3.12 

### ISSUE THREAD

**Issue by logicappsource** [moltin/react-demo-store#44]
I tried to run 

yarn upgrade @moltin/sdk 
npm install --save @moltin/sdk 

Why does it fail ?

**Comment by notrab** [comment]
Hi @logicappsource 

I was able to upgrade the SDK successfully inside a legacy project of mine.

I expect the issue you're running into is the use of `Cart`.

The react demo store uses `2.3.0` but there has been a breaking change since the demo was created.

I'd recommend you look at the [NextJS demo store](https://github.com/moltin-examples/nextjs-demo-store) on how to use the newer version of the SDK.

I hope this helps 😄
